[project]
name = "orpheus-chat-webui"
version = "0.0.0"
description = "Orpheus Chat WebUI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastrtc[stt,tts,vad]==0.0.16",
    "openai==1.67.0",
    "snac==1.2.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
